### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by shakdb** [GreenLightning/advent-of-code-downloader#1] opened 2021-12-13 09:20 UTC
Running this on Windows with the session-key I get the error message:
  "The system cannot find the path specified."

Running without the session-key I get instructions on how to provide the session-key.

**Comment by GreenLightning** [comment] 2021-12-13 18:23
What is the exact command that you are running? Are you using a configuration file?

Usually this kind of error has the form `open <filename>: The system cannot find the path specified.` Do you get any other output?

Are you familiar with Go or are you using the executable from the release?

**Comment by shakdb** [comment] 2021-12-17 06:21
The exact command I ran is:
.\aocdl-windows\aocdl.exe -year 2021 -day 13 -force

I used a configuration file to specify the session-key.
For the above command, the only output was:
"The system cannot find the path specified."

FYI, I was able to run 'curl' on Cygwin to download the AoC input, as specified here:
https://www.reddit.com/r/adventofcode/comments/a2vonl/how_to_download_inputs_with_a_script/

**Comment by GreenLightning** [comment] 2021-12-17 09:28
As far as I know `aocdl` cannot produce this error message without additional information (such as `open <filename>:`). However, Windows will give you that error message if you forget the leading dot or misspell the folder name of the executable (e.g. `.\aocdl-window\aocdl.exe ...`) or if the folder does not exists (e.g. if you are already inside `aocdl-windows`).

Can you reproduce this issue while making sure that the path to the executable is correct?

**Comment by shakdb** [comment] 2021-12-17 10:30
![image](https://user-images.githubusercontent.com/62305046/146530671-c4cde09a-04c6-4484-8651-03fc8b4e4244.png)

Image of command + output

**Comment by GreenLightning** [comment] 2021-12-17 12:42
Turns out I was wrong. I have made a new release that hopefully fixes this issue (I am still not able to reproduce it 100%). Would you please be so kind to test it?

**Comment by jofafrazze** [comment] 2021-12-17 14:36
I had the exact same problem as @shakdb, but it disappeared with this new 1.0.1 release. Thanks! (I'm on Windows 10)

**Comment by GreenLightning** [comment] 2021-12-17 19:50
I am now able to reproduce the exact error message and can confirm that 1.0.1 fixes it, so I will close this issue now. Thank you very much for reporting this problem to me!

**Closed as completed by GreenLightning** 2021-12-17 19:50 UTC
